### ISSUE TITLE
Permissions bug

### ISSUE THREAD

**Issue by sjplautz** [sleighzy/k3s-traefik-v2-kubernetes-crd#23]
Permissions bug. 

The current configuration of 005-deployment.yaml leads to a permissions issue, barring the creation of the defined certificate resolver. The acme.json certificate is stored in the defined pv, which is mounted at /etc/traefik/certs. As /etc is a root folder, mounting the pv here leads to access denied during container spinup due to the deployment being given a security context of nobody:nogroup. Either permissions to the volume need to be explicitly added, or the container must be run as root to bypass this issue.

```yml
securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            # Run the container as nobody:nogroup
            runAsUser: 65534
            runAsGroup: 65534

volumeMounts:
            - name: certificates
              mountPath: /etc/traefik/certs
```
