### ISSUE TITLE
404 not found on dashboard

### ISSUE THREAD

**Issue by ricgatti** [sleighzy/k3s-traefik-v2-kubernetes-crd#4]
Hi I'm following the guide you write, very useful to avoid the usage of helm.

I have created all resource in your file and the whoami test work correctly I got the same output as yours, but when I try to go on the dashboard with the ingressRoute apply I got `404 not found` error after logging in succeffuly

```
curl localhost/dashboard -H "host:traefik.mydomain.io" -u test
Enter host password for user 'test':
404 page not found
```

This is the IngressRoute that I apply
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: default
spec:
  routes:
    - match: Host(`traefik.mydomain.io`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: tools-auth-sec
```

I got traefik on kube-system namespace and all ingressRoute on default namespace.

Thanks for help
